# VacationPy
----

#### Note
* I didn't push the api_keys file to github.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather = pd.read_csv('Weather_Data.csv')
weather.head()

,City,Country,Latitude,Longitude,Wind Speed (mph),Temperature (Fahrenheit),Humidity,Visibility,Pressure
0,georgetown,MY,5.41,100.34,5.57,80.11,94,20,1010
1,kapaa,US,22.08,-159.32,17.22,78.53,69,75,1022
2,rikitea,PF,-23.12,-134.97,15.14,73.89,73,100,1016
3,bilma,NE,18.69,12.92,14.36,84.92,12,0,1009
4,barrow,US,71.29,-156.79,9.17,12.20,85,1,1025

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

In [4]:
coords = weather[["Latitude", "Longitude"]]
coords

     Latitude  Longitude
0        5.41     100.34
1       22.08    -159.32
2      -23.12    -134.97
3       18.69      12.92
4       71.29    -156.79
..        ...        ...
541     55.70      61.55
542     38.80      42.73
543     29.13      15.95
544      9.19     117.81
545    -17.04     -39.53

[546 rows x 2 columns]

In [5]:
fig = gmaps.figure()
heatmap = gmaps.heatmap_layer(coords, weights = weather.Humidity, dissipating = False)
heatmap.gradient = [(255,228,225), (0,139,139)]
fig.add_layer(heatmap)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
mask_temp = (weather['Temperature (Fahrenheit)'] < 65) & (weather['Temperature (Fahrenheit)'] >= 55)
mask_wind = weather["Wind Speed (mph)"] < 8
mask_cloud = weather.Visibility < 10

combined_mask = mask_temp & mask_wind & mask_cloud
prime_cities = weather.loc[combined_mask].reset_index(drop = True)
prime_cities.City = prime_cities.City.str.title()
prime_cities

,City,Country,Latitude,Longitude,Wind Speed (mph),Temperature (Fahrenheit),Humidity,Visibility,Pressure
0,Jamestown,US,42.10,-79.24,5.82,60.80,41,1,1008
1,Bristol,US,41.83,-71.17,4.70,60.98,67,1,1003
2,Ushtobe,KZ,45.25,77.98,7.27,60.44,58,0,1016
3,Flinders,AU,-34.58,150.86,5.99,62.87,55,0,1021
4,Birjand,IR,32.87,59.22,3.06,61.12,33,0,1011
5,Muros,ES,42.78,-9.06,3.00,61.66,82,0,1006
6,Walvis Bay,NaN,-22.96,14.51,7.52,63.19,65,0,1014
7,Lata,PT,40.16,-8.33,6.93,62.94,88,0,1009
8,Betioky,MG,-23.72,44.38,4.52,63.90,77,0,1018
9,Macae,BR,-22.37,-41.79,2.24,64.40,88,0,1018
10,Marsa Matruh,EG,31.35,27.25,6.17,60.80,82,0,1011
11,Salo,IT,45.61,10.53,5.82,56.50,62,5,1017
12,Longonjo,AO,-12.91,15.25,2.19,59.23,42,0,1016
13,Lichinga,MZ,-13.31,35.24,4.25,55.15,52,0,1017
14,Duxbury,US,42.04,-70.67,3.36,59.67,68,1,1003
15,Uruzgan,AF,32.83,66.00,1.66,58.37,29,0,1014
16,Chingola,ZM,-12.53,27.88,3.96,57.92,58,0,1017
17,Greencastle,US,39.64,-86.86,5.82,56.98,67,1,1014
18,Jiuquan,CN,39.74,98.52,2.42,60.39,29,0,1012
19,Kiama,AU,-34.68,150.87,3.00,62.28,56,0,1026
20,Kang,BW,-23.68,22.79,6.60,61.63,19,0,1018
21,Premia De Mar,ES,41.49,2.37,1.19,62.83,88,5,1016
22,Coquimbo,CL,-29.95,-71.34,3.36,57.20,87,0,1014
23,Balkhash,KZ,46.84,74.98,5.95,57.40,57,0,1014
24,Kibondo,TZ,-3.59,30.72,1.97,58.89,62,0,1015
25,Hun,LY,29.13,15.95,4.92,64.45,46,0,1017

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
name = []
address = []
rating = []

#for each city in the prime cities, bring back the longitude and latitude of the city
for index, row in prime_cities.iterrows():
    params = {
        "radius": 5000,
        "types": "hotel",
        "keyword": "hotel",
        "key": g_key
    }
    lat = prime_cities.Latitude[index]
    long = prime_cities.Longitude[index]

    #search parameters
    params['location'] = f'{lat},{long}'

    #create url and generate json from get request to Google Places API 
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    name_address = requests.get(base_url, params=params).json()

    #had to separate out try/except because for loop was adding in duplicate values for entries 
    #i.e. append name and then if no rating info, append "" for name again in the except block
    try:
        name.append(name_address['results'][0]['name'])
    
    except: 
        name.append("")
        
    try: 
        address.append(name_address['results'][0]['vicinity'])
        
    except:
        address.append("")
        
    try: 
        rating.append(name_address["results"][0]["rating"])
    except:
        rating.append("")

In [8]:
#append rows for hotel, address, and rating
prime_cities["Hotel"] = name
prime_cities["Address"] = address
prime_cities["Rating"] = rating

prime_cities

,City,Country,Latitude,Longitude,Wind Speed (mph),Temperature (Fahrenheit),Humidity,Visibility,Pressure,Hotel,Address,Rating
0,Jamestown,US,42.10,-79.24,5.82,60.80,41,1,1008,Chautauqua Harbor Hotel,"10 Dunham Ave, Celoron",4.6
1,Bristol,US,41.83,-71.17,4.70,60.98,67,1,1003,,,
2,Ushtobe,KZ,45.25,77.98,7.27,60.44,58,0,1016,,,
3,Flinders,AU,-34.58,150.86,5.99,62.87,55,0,1021,Lakeview Hotel Motel,"4 Government Rd, Oak Flats",3.8
4,Birjand,IR,32.87,59.22,3.06,61.12,33,0,1011,Sepehr Hotel,Birjand,4
5,Muros,ES,42.78,-9.06,3.00,61.66,82,0,1006,Hotel La Muradana,"Av. Castelao, 99, Muros",4.2
6,Walvis Bay,NaN,-22.96,14.51,7.52,63.19,65,0,1014,Protea Hotel by Marriott Walvis Bay Pelican Bay,"The Esplanade, Walvis Bay",4
7,Lata,PT,40.16,-8.33,6.93,62.94,88,0,1009,Quinta do Outeiro,"Rua do Outeiro 18, Vila Nova de Poiares",4.9
8,Betioky,MG,-23.72,44.38,4.52,63.90,77,0,1018,Betioky,"Betioky, Madagascar",
9,Macae,BR,-22.37,-41.79,2.24,64.40,88,0,1018,Royal Macaé Palace Hotel,"Av. Atlântica, 1642 - Cavaleiros, Macaé",4.5
10,Marsa Matruh,EG,31.35,27.25,6.17,60.80,82,0,1011,Beau Site,El Corniche Street Qesm,4.2
11,Salo,IT,45.61,10.53,5.82,56.50,62,5,1017,Hotel Spiaggia d'Oro,"Via Spiaggia D'Oro, 15, Salò",4.6
12,Longonjo,AO,-12.91,15.25,2.19,59.23,42,0,1016,,,
13,Lichinga,MZ,-13.31,35.24,4.25,55.15,52,0,1017,Girassol Lichinga,"Rua Filipe Samuel Magaia, Lichinga",3.5
14,Duxbury,US,42.04,-70.67,3.36,59.67,68,1,1003,Winsor House Inn,"390 Washington St, Duxbury",4.3
15,Uruzgan,AF,32.83,66.00,1.66,58.37,29,0,1014,,,
16,Chingola,ZM,-12.53,27.88,3.96,57.92,58,0,1017,Icon Hotel,"Kabundi Rd, Chingola",4
17,Greencastle,US,39.64,-86.86,5.82,56.98,67,1,1014,Inn at DePauw,"2 W Seminary St, Greencastle",4.5
18,Jiuquan,CN,39.74,98.52,2.42,60.39,29,0,1012,Longteng Hotel,"31 E Ring Rd S, Suzhou District, Jiuquan",3
19,Kiama,AU,-34.68,150.87,3.00,62.28,56,0,1026,The Sebel Kiama Harbourside,"31 Shoalhaven St, Kiama",4.2
20,Kang,BW,-23.68,22.79,6.60,61.63,19,0,1018,Kang Ultra Stop,"11015 Kazungula, Gaborone",3.8
21,Premia De Mar,ES,41.49,2.37,1.19,62.83,88,5,1016,Hotel Sorli Emocions,"Carrer Lluís Jordà Cardona, 2, Vilassar de Dalt",4.2
22,Coquimbo,CL,-29.95,-71.34,3.36,57.20,87,0,1014,Condiminio Marina Sol,"Avenida, Peñuelas Nte 186 -196, Coquimbo",4.5
23,Balkhash,KZ,46.84,74.98,5.95,57.40,57,0,1014,Guest House Comfort-House-Balkhash,"квартал Ветеранов 1 А, Balkhash",4
24,Kibondo,TZ,-3.59,30.72,1.97,58.89,62,0,1015,Swidish Modern Hotel,Kibondo,3.8
25,Hun,LY,29.13,15.95,4.92,64.45,46,0,1017,Al Nakhel Hotel,Libya,2.7

In [9]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel}</dd>
<dt>City</dt><dd>{City}, {Country}</dd>
<dt>Address</dt><dd>{Address}</dd>
<dt>Rating</dt><dd>{Rating} Stars</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in prime_cities.iterrows()]
locations = prime_cities[["Latitude", "Longitude"]]

In [10]:
# Add marker layer ontop of heat map
marker = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig.add_layer(marker)

fig
# Display figure

Figure(layout=FigureLayout(height='420px'))